const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const assert = require('node:assert/strict');
(async () => {
  const browser = await chromium.launch({ channel: 'msedge', headless: true });
  try {
    const page = await browser.newPage({ viewport: { width: 1440, height: 1100 } });
    const errors = [];
    page.on('pageerror', error => errors.push(error.message));
    await page.goto('http://127.0.0.1:8877');
    await page.locator('#demo-banner').waitFor({ state: 'visible' });
    await page.getByRole('button', { name: '01 - Introduzione al progetto', exact: false }).click();
    await page.locator('#notes-tab').click();
    await page.locator('#notes-preview').waitFor({ state: 'visible' });
    await page.locator('#notes-edit').click();
    const source = '# Il progetto di comunicazione\n\nAppunti dimostrativi per verificare la nuova impaginazione.\n\n## 1. Obiettivo e destinatari\n\nIl progetto parte da un **obiettivo chiaro** e dall’identificazione del pubblico. Le scelte visive devono sostenere il messaggio.\n\n- Definire cosa si vuole comunicare.\n- Individuare il pubblico di riferimento.\n  - Considerare il contesto di utilizzo.\n\n## 2. Procedura di lavoro\n\n1. Analizzare la richiesta.\n2. Sviluppare una proposta coerente.\n3. Verificare la leggibilità del risultato.\n\n> Distinguere le informazioni confermate dalle ipotesi ancora da verificare.\n\n## Da ricordare\n\nLa **gerarchia visiva** aiuta a riconoscere le informazioni principali.\n';
    await page.locator('#editor').fill(source);
    assert.equal(await page.locator('#print-notes').isEnabled(), false);
    assert.equal(await page.locator('#download-markdown').getAttribute('href'), null);
    await page.locator('#notes-read').click();
    assert.equal(await page.locator('#notes-preview h1').textContent(), 'Il progetto di comunicazione');
    assert.equal(await page.locator('#notes-preview h2').count(), 3);
    assert.equal(await page.locator('#notes-preview strong').count(), 2);
    assert.equal(await page.locator('#notes-preview ul ul').count(), 1);
    assert.equal(await page.locator('#notes-preview ol li').count(), 3);
    assert.equal(await page.locator('#dirty').isVisible(), true);
    await page.locator('#notes-edit').click();
    assert.equal(await page.locator('#editor').inputValue(), source);
    await page.locator('#editor').evaluate(el => {
      const start = el.value.indexOf('Appunti dimostrativi');
      el.setSelectionRange(start, start + 'Appunti dimostrativi'.length);
    });
    await page.locator('[data-format="bold"]').click();
    assert.match(await page.locator('#editor').inputValue(), /\*\*Appunti dimostrativi\*\*/);
    await page.locator('#notes-read').click();
    await page.keyboard.press('Control+s');
    await page.locator('#dirty').waitFor({ state: 'hidden' });
    const download = await page.request.get(await page.locator('#download-markdown').evaluate(el => el.href));
    assert.match(await download.text(), /## 2\. Procedura/);
    await page.locator('#export-menu summary').click();
    assert.equal(await page.locator('#download').isVisible(), true);
    assert.equal(await page.locator('#download-notes').isVisible(), true);
    assert.equal(await page.locator('#download-markdown').isVisible(), true);
    assert.match(await page.locator('#download').getAttribute('href'), /download\/transcript$/);
    assert.match(await page.locator('#download-notes').getAttribute('href'), /download\/notes$/);
    await page.keyboard.press('Escape');
    assert.equal(await page.locator('#export-menu').getAttribute('open'), null);
    await page.reload();
    await page.getByRole('button', { name: '01 - Introduzione al progetto', exact: false }).click();
    await page.locator('#notes-tab').click();
    await page.locator('#notes-preview h1').waitFor();
    assert.equal(await page.locator('#notes-preview strong').count(), 3);
    // Rendering never interprets lesson HTML or executes links/scripts.
    await page.locator('#notes-edit').click();
    const saved = await page.locator('#editor').inputValue();
    await page.locator('#editor').fill(saved + '\n<img src=x onerror="window.injected=1">\n<script>window.injected=1</script>\n[jump](javascript:alert(1))');
    await page.locator('#notes-read').click();
    assert.equal(await page.locator('#notes-preview img, #notes-preview script, #notes-preview a').count(), 0);
    assert.equal(await page.evaluate(() => window.injected), undefined);
    assert.match(await page.locator('#notes-preview').textContent(), /<img/);
    await page.locator('#notes-edit').click();
    await page.locator('#editor').fill(saved);
    await page.locator('#notes-read').click();
    await page.screenshot({ path: 'test-artifacts/notes-desktop.png', fullPage: true });
    await page.setViewportSize({ width: 390, height: 844 });
    await page.locator('#export-menu summary').click();
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
    await page.screenshot({ path: 'test-artifacts/notes-mobile.png', fullPage: true });
    await page.keyboard.press('Escape');
    await page.setViewportSize({ width: 900, height: 1200 });
    await page.locator('#transcript-tab').click();
    const transcript = await page.locator('#editor').inputValue();
    await page.evaluate(() => { window.print = () => { window.printCalled = true; }; });
    await page.locator('#export-menu summary').click();
    await page.locator('#print-notes').click();
    assert.equal(await page.evaluate(() => window.printCalled), true);
    await page.emulateMedia({ media: 'print' });
    assert.equal(await page.locator('.archive').isVisible(), false);
    assert.equal(await page.locator('#notes-tools').isVisible(), false);
    assert.equal(await page.locator('#notes-preview').isVisible(), true);
    assert.match(await page.locator('#notes-preview').textContent(), /Il progetto di comunicazione/);
    await page.screenshot({ path: 'test-artifacts/notes-print-preview.png', fullPage: true });
    await page.emulateMedia({ media: 'screen' });
    await page.evaluate(() => window.dispatchEvent(new Event('afterprint')));
    assert.equal(await page.locator('#editor').inputValue(), transcript);
    assert.equal(await page.locator('#transcript-tab').getAttribute('aria-selected'), 'true');
    assert.deepEqual(errors, []);
    console.log('PASS: formatted notes, nested lists, edit/read draft, formatting toolbar, save/reload, Markdown export, literal HTML safety, mobile, print stylesheet.');
  } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; });
